# Generated by Django 3.1.4 on 2021-01-09 21:54

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_lo_response", models.BooleanField(null=True)),
                ("user_hi_response", models.BooleanField(null=True)),
                (
                    "user_hi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchstatus_hi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_lo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchstatus_lo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="matchstatus",
            constraint=models.CheckConstraint(
                check=models.Q(
                    user_lo_id__lt=django.db.models.expressions.F("user_hi_id")
                ),
                name="user_lo_lt_user_hi",
            ),
        ),
    ]
