# Generated by Django 3.1.4 on 2021-02-08 13:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_matchstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.AddField(
            model_name="video",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_videos",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_videos",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(null=True, upload_to="videos/", verbose_name=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "phone_number",
                    models.CharField(max_length=10, null=True, unique=True),
                ),
                ("age", models.PositiveIntegerField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
