# Generated by Django 3.1.4 on 2021-02-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.AddField(
            model_name="video",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_videos",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_videos",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(null=True, upload_to="videos/", verbose_name=""),
        ),
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
