# Generated by Django 3.1.4 on 2021-01-31 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_auto_20210119_2106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.AddField(
            model_name="video",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_videos",
                to="auth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_videos",
                to="auth.user",
            ),
            preserve_default=False,
        ),
    ]
