# Generated by Django 3.1.4 on 2021-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20210131_1547"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
