# Generated by Django 3.1.4 on 2021-02-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_update_profile"),
        ("api", "0005_auto_20210220_1518"),
    ]

    operations = []
