# Generated by Django 3.1.4 on 2021-03-02 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0006_merge_20210225_2009"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user_ptr",
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.user",
            ),
            preserve_default=False,
        ),
    ]
