# Generated by Django 3.1.4 on 2021-03-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20210306_1641"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
