# Generated by Django 3.1.4 on 2021-03-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_profile_interests"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.profile",
                        verbose_name="related profile",
                    ),
                ),
                (
                    "first_name_privacy",
                    models.CharField(
                        choices=[("PU", "Public"), ("PR", "Private"), ("HI", "Hidden")],
                        default="PU",
                        max_length=2,
                    ),
                ),
                (
                    "last_name_privacy",
                    models.CharField(
                        choices=[("PU", "Public"), ("PR", "Private"), ("HI", "Hidden")],
                        default="PU",
                        max_length=2,
                    ),
                ),
                (
                    "birth_date_privacy",
                    models.CharField(
                        choices=[("PU", "Public"), ("PR", "Private"), ("HI", "Hidden")],
                        default="PR",
                        max_length=2,
                    ),
                ),
                (
                    "gender_privacy",
                    models.CharField(
                        choices=[("PU", "Public"), ("PR", "Private"), ("HI", "Hidden")],
                        default="PR",
                        max_length=2,
                    ),
                ),
                (
                    "interests_privacy",
                    models.CharField(
                        choices=[("PU", "Public"), ("PR", "Private"), ("HI", "Hidden")],
                        default="PU",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
