# Generated by Django 3.1.4 on 2021-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210402_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_file',
            field=models.FileField(null=True, upload_to='images/', verbose_name='profile picture'),
        ),
    ]
