# Generated by Django 3.1.4 on 2021-04-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_auto_20210402_2245"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacy",
            options={"verbose_name_plural": "Privacy"},
        ),
        migrations.AlterField(
            model_name="report",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin handling the report",
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="video",
            field=models.ForeignKey(
                blank=True,
                help_text="The offending video",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.video",
            ),
        ),
    ]
