# Generated by Django 3.1.4 on 2021-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20210402_2245"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("message", models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("W", "Website"),
                            ("Pp", "Penpal"),
                            ("P", "Performance"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=2000)),
                ("email", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
