# Generated by Django 3.1.4 on 2021-03-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20210321_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image_file",
            field=models.FileField(
                null=True, upload_to="images/", verbose_name="profile picture"
            ),
        ),
    ]
