# Generated by Django 3.1.4 on 2021-04-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_contactus_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(),
        ),
    ]
