# Generated by Django 3.1.4 on 2021-04-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_profile_paused"),
        ("api", "0011_profile_image"),
    ]

    operations = []
