# Generated by Django 3.1.4 on 2021-05-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20210428_0028"),
        ("api", "0013_merge_20210427_2130"),
    ]

    operations = []
