#!/bin/sh

# Find the python virtual environment
# This assumes there is only 1 'pyvenv.cfg' under the project tree
venvdir="$(find . -name pyvenv.cfg -type f -exec dirname {} \;)"
if [ -z "$venvdir" -o "$venvdir" = '.' ]; then
    >&2 echo 'pre-commit: could not find python virtual environment'
    >&2 echo '    Make sure you have a created a python virtual environment'
    >&2 echo '    for this project. See the README for instructions on how to'
    >&2 echo '    setup up the development environment'
    exit 1
fi

[ -d "$venvdir/bin" ] && bindir="bin" || bindir="Scripts"
err=0

# Check python source code style
staged_files="$(git diff --staged --name-only --diff-filter=ACMR | egrep '\.pyi?$')"
if [ -n "$staged_files" ]; then
    echo Running isort
    "$venvdir/$bindir/isort" --profile black --check-only $staged_files
    err=$((err|$?))
    echo Running black
    "$venvdir/$bindir/black" --check $staged_files
    err=$((err|$?))
    echo Running flake8
    "$venvdir/$bindir/flake8" $staged_files
    err=$((err|$?))
fi

# Check typescript source code style
staged_files="$(git diff --staged --name-only --diff-filter=ACMR | egrep '\.tsx?$' | sed s,frontend/,,)"
if [ -n "$staged_files" ]; then
    cd frontend
    echo Running prettier
    npm run --silent format-check -- $staged_files
    err=$((err|$?))
    echo Running eslint
    npm run --silent lint-check -- $staged_files
    err=$((err|$?))
    cd -
fi

exit $err
