#!/bin/sh

# Find the python virtual environment
# This assumes there is only 1 'pyvenv.cfg' under the project tree
venvdir="$(find -name pyvenv.cfg -type f -exec dirname {} \;)"
if [ -z "$venvdir" -o "$venvdir" = '.' ]; then
    >&2 echo 'pre-commit: could not find python virtual environment'
    >&2 echo '    Make sure you have a created a python virtual environment'
    >&2 echo '    for this project. See the README for instructions on how to'
    >&2 echo '    setup up the development environment'
    exit 1
fi

err=0

# Check python source code style
staged_files="$(git diff --staged --name-only --diff-filter=ACMR | grep .py$)"
if [ -n "$staged_files" ]; then
    echo Running isort
    "$venvdir/bin/isort" --profile black --check-only $staged_files
    err=$((err|$?))
    echo Running black
    "$venvdir/bin/black" --check $staged_files
    err=$((err|$?))
    echo Running flake8
    "$venvdir/bin/flake8" $staged_files
    err=$((err|$?))
fi

# TODO Add typescript style checking

exit $err

